### ISSUE TITLE
newConversation is returning a empty object despite the ticket is created with success in helpScout

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#16]
Using the example you gave "var newConv = client.CreateConversation(new Conversation..." the conversation is created in the helpScout platform but the object returned is empty including the newConv.number that I was using to get the number of the ticket.

Don't know if helpScout has changed anything that might have broken your implementation.

Any help would be great because we depend on your implementation to use helpSocut in .net.

Thanks

**Comment by mathieukempe** [comment]
Unless you set reload t= false it should reload the conversation 
```
 public Conversation CreateConversation(Conversation conversation, bool imported = false, bool autoReply = false, bool reload = true)
  
```

Unless Helpscout changed something it should work

**Comment by sergiopfaria** [comment]
Didn't change any of the optional parameters. 
I'm going to ask helpscout if they change anything recently and let you know.

**Comment by sergiopfaria** [comment]
I've being testing and helpscout is returning the correct info but for some reason the deserialization is not occuring at  T result = JsonConvert.DeserializeObject<T>(body);
 
After calling CreateConversation() the endpoint="conversations.json" is correctly called and the post response.IsSuccessStatusCode is valid, request.Reload is true so the  T result = JsonConvert.DeserializeObject<T>(body); is executed but it doesn't work and the return value is null.

Can you please help

**Comment by sergiopfaria** [comment]
I've update to 4.1.0 version and confirm that the problem is fixed.

Thanks Mathieu for all the support
