### ISSUE TITLE
Ending TLS 1.0 Support

### ISSUE THREAD

**Issue by SimformSahil** [Selz/HelpScoutNet#17]
HelpScout has been discontinuing support for TLS 1.0 connections. I wanted to check are any updates available in the library for the same?

Here is the original email received from HelpScout:
![image](https://user-images.githubusercontent.com/8737256/27830733-65db8190-60e5-11e7-9ef3-66a082e7d474.png)

Our system is tightly integrated with your library, please let me know what can we do about this TLS support and how we can migrate to other versions supporting HelpScout API calls?

**Comment by mathieukempe** [comment]
If you upgrade to the version 5.0 of the library, I've changed the project to Target the framework 4.6 which support tls1.2 by default

http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

**Comment by SimformSahil** [comment]
Hey, thanks for your reply. I was about to send you the same link so you can update the target framework to v4.0 so it takes tls1.2 by default and we can use the new version of the library.

As you have already done that, we'll update the library to v5.0 and that should work.
