### ISSUE TITLE
Exception thrown when try to update a conversation

### ISSUE THREAD

**Issue by themagicis** [Selz/HelpScoutNet#19]
An exception is thrown when UpdateConversation is called:
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'HelpScoutNet.Model.ThreadState'. Path 'item.threads[0].state', line 1, position 1789. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
Setting parameter reload to false fixes it, which means that it fails to deserialize the api response.

**Comment by AaronToledoPIDS** [comment]
Similar/same issue with hidden threads. 

We are seeing the function `GetConversation()` throw:

`Error converting value "hidden" to type 'HelpScoutNet.Model.ThreadState'. Path 'item.threads[1].state', line 1, position 2643.`

Adding 'hidden' to the ThreadState enum looks to have solved this.

Thanks.
