### ISSUE TITLE
client.UpdateConversation returning "Input could not be validated"

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#2]
I'm trying to update a conversation but getting the error "Input could not be validated" but don't know why.

I'm using the code

  Dim newConv = client.UpdateConversation(New Conversation() With {
            .Subject = "Testing the Helpscout API Mathieu",
            .Mailbox = New MailboxRef() With {
                .Id = mymailboxid
            },
            .Status = ConversationStatus.active,
            .Owner = New Person() With {
                .Id = operatorId,
                .Type = PersonType.user
            }
        })

Any clues?

**Comment by Soulfire86** [comment]
@mathieukempe Looks like the endpoint for UpdateConversation was missing the id part. My pull request should fix @sergiopfaria issue.

**Comment by mathieukempe** [comment]
Thanks @Soulfire86 ! I've merged the pull request
