### ISSUE TITLE
HelpScout API 2.0  (API 1.0 will be shut down on June 6th, 2019)

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#28]
HelpScout is shutting down API 1.0 on June 6th, 2019.
Is there any plans to update helpScoutNet to API 2.0?

**Comment by mathieukempe** [comment]
I started having a look today, there is a few thing that need to be changed, (pagination, auth)
I will look at how much work is involved

**Comment by kaagati** [comment]
HelpScout api 2.0 is now implemented in version 7.0.0
