### ISSUE TITLE
API 2.0 - Can't initialize client

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#35]
I'm moving to V7 that uses API 2.0 but I'm having problems initializing the client.
I'm in a develop environment using IIS Express and as helpScout app settings doesn't allow to configure redirectURI as http://localhost:57327 I use instead http://127.0.0.1:57327 so I think this should not be the problem.

I've debug step by step and helpScoutNet API is getting the token with success but then nothing happens after  Gate.Release() on line 39 of HelpScoutzAPI.cs (code bellow)

Any ideias what the problem could be?
Thanks

public async Task<Token> GetToken()
        {
            try
            {
                await Gate.WaitAsync().ConfigureAwait(false);
                return token ?? (token = (await DoHttp().ConfigureAwait(false)).Record);
            }
            finally
            {
                Gate.Release();
            }
        }

**Comment by kaagati** [comment]
It is quite difficult to say looking at the example you have posted. Could you please post your example at minimum.

**Comment by sergiopfaria** [comment]
The code I'm using is bellow. I call the function on page load of our web application but it stays forever on await client.GetToken(true);

async System.Threading.Tasks.Task<int> testAsync()
    {
        var client = new HelpScoutApiClient("xxxxxxxx", "yyyyyyy");
        await client.GetToken(true);

        Response.Write("finish");
        return 1;
    }

**Comment by kaagati** [comment]
I am still not able to reproduce it on 7.0 and 7.1 version, Here is what I have tested.

`
public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public async Task<ActionResult> Contact()
        {
            await testAsync();
            ViewBag.Message = "Your contact page.";

            return View();
        }
        async System.Threading.Tasks.Task testAsync()
        {
            var client = new HelpScoutApiClient("30e629c885034408ac83f2f67a4d26f9", "52d2d72e1ab145a7b473e7c0a1fe7a94");
            var token = await client.GetToken(true);

            Response.Write("finish");
            
        }
    }
`

**Comment by sergiopfaria** [comment]
What do you have configured in helpScout Your Profile | My Apps in the field redirection URL?
I have http://127.0.0.1:57327.

At first i thought it might be because i was using 127.0.0.1 and a port number but i've uploaded to a test subdomain in a production server and the result was the same.

**Comment by sergiopfaria** [comment]
Thanks @kaagati
I'm not using an mvc application but your code point me in the right direction.
