### ISSUE TITLE
import parameter is not being taken in account

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#4]
When creating a new thread, even if the import parameter is set to true, helpscout will send an email. 
I spoke with @craig-davis from helpScout and he confirmed the import parameter appears to be unused.

**Comment by craig-davis** [comment]
I believe that the `import` parameter [is not being used](https://github.com/Selz/HelpScoutNet/blob/144b474e9c7402bed91514002a813952b3b5c5cc/src/HelpScoutClient.cs#L119) in the call to `Post` on line 123.

**Comment by mathieukempe** [comment]
Sorry for the delay
I'm currently on annual leave, I will have a look as soon as I'm back home

**Comment by craig-davis** [comment]
@mathieukempe Thanks for the update. Much appreciated. 

I found a couple of misspelled methods as well, in particular some methods named `ListConservations *`. You can see them here: https://github.com/Selz/HelpScoutNet/blob/master/src/HelpScoutClient.cs#L67

Thanks for this library!

**Comment by mathieukempe** [comment]
The import flag on thread  is fixed (with the misspelled methods)
