### ISSUE TITLE
attachements

### ISSUE THREAD

**Issue by sergiopfaria** [Selz/HelpScoutNet#5]
I'm having difficulties creating a conversation with an attachment because, as far as i can see in the code, the attachment properties of the code 
 public int Id { get; set; }
        public string MimeType { get; set; }
        public string Filename { get; set; }
        public int Size { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string Url { get; set; }

are different from the helpscout docs
{
    "fileName" : "file.txt",
    "mimeType" : "text/plain",
    "data": "Q1JFQVRFIFRBQkxFIGBoZWxwc2NvdXRfYXR0YWNobWVudHNf..."
}

Do you have an example how to create a new conversation with an attachment (pdf for example)?

Thanks,

**Comment by mathieukempe** [comment]
Helpscout changed their API a few weeks ago, some of those changes included the ability to create an attachment 
This should work in the new version (1.2.0.0) of the library 

To create an attachment
```csharp

Byte[] bytes = File.ReadAllBytes(@"C:\Users\mathieu.kempe.SELZ\Desktop\sift-logo.png");
String file = Convert.ToBase64String(bytes);

string fileHash = client.CreateAttachment(new CreateAttachmentRequest
                                          {
                                             FileName = "sift-logo.png",
                                             MimeType = "image/png",
                                             Data = file
                                          });

```

To add the attachment to a new conversation

```csharp
 var newConv = client.CreateConversation(new Conversation
  {
      ...
      Threads = new List<Thread>{
                        new Thread
                        {
                            ...
                            Attachments = new List<Attachment>
                            {
                                new Attachment
                                {
                                    Hash = fileHash
                                }
                            }
                        }
                     }
               });
               
```

**Comment by sergiopfaria** [comment]
Perfect, working like a charm!
Thanks for the support and for the great lib
