### ISSUE TITLE
No support for reports

### ISSUE THREAD

**Issue by douglasg14b** [Selz/HelpScoutNet#6]
Looks like HelpScout just added reports to their API documentation, super exciting stuff. Any plan for reports support?

**Comment by mathieukempe** [comment]
I'm planning to start working on the report stuff next week but not sure how long it will take me to cover it all

**Comment by douglasg14b** [comment]
Sure, I branched it and am making the classes for each report object atm. Once I finish those (maybe tonight) I'll make a pull request if you want them. I do however make a file for each class under a reports folder, rather than multiple classes in a single .cs file. Easy enough to change though.

**Comment by douglasg14b** [comment]
Model is made, just creating the requests and methods. Reports really messes with the current types, since it has a different Tag, User, Paged...etc Than the rest of the API.

**Comment by mathieukempe** [comment]
Awesome! I didn't have time to work on it at all this week. Thanks for helping with that
